
const crewingData = {
    h1: "Crewing",
    s1: "Expert Crew Management for Smooth Operations at Sea",
    d1: "Expert Crew Management for Smooth Operations at Sea. Our meticulous crew selection process ensures skilled personnel with qualifications, experience, and competency. Safety of the ship, cargo, and crew is paramount, with compliance to all regulations. We maintain CBA's and SEA, handle crew payrolls, and conduct timely reviews to ensure top-notch performance in accordance with MLC 2006.",
    img: "crewing-image.png",
    h2: "Crewing Services:",
    s2: "Nurturing Excellence for Seamless Maritime Endeavors",
    d2: "At our company, we pride ourselves on delivering top-notch crewing services, meticulously tailored to meet the unique requirements of vessel trading. Our team of experts works diligently to ensure the selection of highly qualified, experienced, and competent crew members, fostering efficient vessel operations and upholding the safety of both ship and crew. We leave no stone unturned when it comes to compliance and certification. Every crew member is thoroughly vetted to hold all necessary valid certificates, including health, flag, and travel documents, in strict adherence to the vessel's trading regulations. Managing Crew Employment Agreements and Seafarers' Employment Agreements is a key aspect of our responsibility. We actively monitor and control crew payrolls, ensuring timely payments, and strict adherence to the terms and conditions of these agreements. As part of our commitment to excellence, we conduct regular audits and reviews to guarantee compliance with the Maritime Labour Convention (MLC) of 2006. The MLC sets the benchmark for seafarers' rights and welfare, and we make certain all conditions are diligently met to safeguard the well-being of our crew.  Our dedication extends to handling all aspects of crew management. We meticulously monitor crew contract periods and arrange timely reliefs upon contract completion, ensuring smooth crew transitions at suitable ports. From coordinating joining and repatriation logistics, air tickets, agency handling, to reliable transportation, we ensure a seamless experience for our valued crew. When it comes to addressing crew matters, our expert team liaises closely with the Crewing Department/Agency. We handle disputes, disciplinary or incompetence matters, and ensure prompt medical attention and claims support. With our comprehensive crewing services, rest assured that your vessel will be manned by a competent and harmonious crew, enabling you to navigate the high seas with confidence and efficiency. Experience the pinnacle of maritime excellence with our bespoke crew management solutions."
}

export default crewingData;